### ISSUE TITLE
How to find all reactions represented in GO involving nitrate as a substrate or product?

### ISSUE THREAD

**Issue by realmarcin** [geneontology/helpdesk#333]
Hello,

I am trying to find a relevant set of GO terms for functions related to nitrate. There is the obvious nitrate reduction, however there are a few variants of these pathways and they also exist as dissimilatory (respiration using nitrate as electron acceptor) and assimilatory (conversion of inorganic nitrogen to organic) reactions, as well as in plants and microbes using different enzymes/pathways.

For reference here are the MetaCyc entries for 'nitrate reduction':
https://metacyc.org/META/NEW-IMAGE?type=ECOCYC-CLASS&object=Nitrate-Reduction

and 'nitrate assimilation:
https://biocyc.org/META/NEW-IMAGE?type=ECOCYC-CLASS&object=GO:0042128

EBI QuickGO also provides cooccurring terms from annotations (for 'nitrate assimilation'):
https://www.ebi.ac.uk/QuickGO/term/GO:0042128

**Comment by cmungall** [comment]
We hope to have all the information necessary to do this query in go-plus soon. But for now to get all the relevant reactions it's necessary to merge go and rhea or do a federated sparql query. @balhoff do you have any recommendations on how best to proceed?

(@realmarcin is fairly conversant in sparql)

This question brings up a number of interesting questions for the ontology group and go-cams

If we look at:

```yaml
id: GO:0042128
name: nitrate assimilation
namespace: biological_process
def: "The nitrogen metabolic process that encompasses the uptake of nitrate from the environment and reduction to ammonia, and results in the incorporation of nitrogen derived from nitrate into cellular substances." [GOC:das, GOC:mah, PMID:10542156, PMID:8122899]
synonym: "assimilatory nitrate reduction" EXACT []
xref: MetaCyc:PWY-381
is_a: GO:0042126 ! nitrate metabolic process
is_a: GO:0071941 ! nitrogen cycle metabolic process
```

Who chose PWY-381 and why? There are multiple different assimilatory nitrate reduction pathways in MetaCyc, the choice of 381 seems arbitrary

in contrast we have no pathways linked for 

```yaml
id: GO:0043602
name: nitrate catabolic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the breakdown of nitrates, inorganic or organic salts and esters of nitric acid." [GOC:jl]
synonym: "nitrate disassimilation" EXACT []
synonym: "nitrate dissimilation" EXACT []
is_a: GO:0044270 ! cellular nitrogen compound catabolic process
intersection_of: GO:0009056 ! catabolic process
intersection_of: has_primary_input CHEBI:17632 ! nitrate
```

This is oddly generic - catabolized to what? 

I think our representation of nitrogen cycling reactions is in need of review, e.g. https://github.com/geneontology/go-ontology/issues/22119

here is a good review: https://www.nature.com/articles/nrmicro.2018.9?WT.feed_name=subjects_microbiology

And the metacyc classification and subtypes are good:
https://biocyc.org/META/NEW-IMAGE?type=ECOCYC-CLASS&object=Nitrate-Reduction

@realmarcin may be able to help us with some microbiome use cases
