### ISSUE TITLE
Links to PANTHER in AmiGO broken (was: IL3 annotation as protein tyrosine kinase activity)

### ISSUE THREAD

**Issue by jpinero** [geneontology/helpdesk#95]
Hi, 
I was wondering if the annotation of: 

IL3 | Interleukin-3 |   | protein tyrosine kinase activity |   | Reactome | Homo sapiens | TAS

is correct. 
Also, this link is broken
http://www.pantherdb.org/panther/lookupId.jsp?id=PTHR10079

best,
janet

**Comment by kltm** [comment]
@jpinero 

Thank you for taking the time to report your issue. On what page did you find the above annotation and broken PANTHER link?

**Comment by jpinero** [comment]
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P08700
in the column PANTHER family

**Comment by kltm** [comment]
@jpinero 

Thank you for the update. 
I'm going to split your Reactome annotation question into a different helpdesk item so we don't get confused.

**Comment by kltm** [comment]
Hm. This is the current "correct" form as found in our configuration metadata. @mugitty would there possibly have been an update that was not reflected in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml ?
```yaml
- database: PANTHER
  name: Protein ANalysis THrough Evolutionary Relationships Classification System
  generic_urls:
    - http://www.pantherdb.org/
  entity_types:
    - type_name: protein family
      type_id: NCIT:C20130
      id_syntax: PTN[0-9]{9}|PTHR[0-9]{5}_[A-Z0-9]+
      url_syntax: http://www.pantherdb.org/panther/lookupId.jsp?id=[example_id]
      example_id: PANTHER:PTHR11455
      example_url: http://www.pantherdb.org/panther/lookupId.jsp?id=PTHR10000
```
